#!/usr/bin/python3

import os
import shlex
import subprocess
import sys
import threading

sys.path.append("../scripts")
import split

import data_util

# Returns True if everything we need is here, False otherwise.
def check_dependencies():
  try:
    subprocess.check_call(shlex.split("sass --version"))
  except (subprocess.CalledProcessError, OSError):
    print("Please install 'sass' first.")
    return False
  return True

def run_sass_precompiler():
  input_files = [f for f in os.listdir("css") if f.endswith(".scss")]
  if not len(input_files):
    return None
  return subprocess.call(shlex.split("sass --watch css:css"))

def run_http_server():
  # Uses port 8000 by default.
  return subprocess.call(shlex.split("python3 -m http.server"))

if not check_dependencies():
  sys.exit(1)

data_util.prepare_for_local_development()

try:
  threads = []
  http = threading.Thread(target=run_http_server)
  sass = threading.Thread(target=run_sass_precompiler)
  http.start()
  sass.start()
  http.join()
  sass.join()

except KeyboardInterrupt as e:
  print("Shutting down...")
  sys.exit(0)
